admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }

admin_carts_list:
    path:     /carts
    defaults: { _controller: AdminBundle:Admin:cartsList }

admin_being_treated_carts:
    path:     /carts/beingtreated
    defaults: { _controller: AdminBundle:Admin:beingTreatedCartsList }

admin_treated_carts:
    path:     /carts/treated
    defaults: { _controller: AdminBundle:Admin:treatedCartsList }

admin_treat_cart:
    path:     /carts/treat/{id}
    defaults: { _controller: AdminBundle:Admin:treatCart }
    requirements:
        id: \d+