# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    cart.twig_extension:
          class:  AppBundle\Twig\CartExtension
          arguments:
            doctrine: "@doctrine"
            container: "@service_container"
          tags:
              - { name: twig.extension }
