admin_product_index:
    path:     /
    defaults: { _controller: "AdminBundle:Product:index" }
    methods:  GET

admin_product_stock:
    path:     /stock
    defaults: { _controller: "AdminBundle:Product:stock" }
    methods:  GET

admin_product_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Product:show" }
    methods:  GET

admin_product_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Product:new" }
    methods:  [GET, POST]

admin_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Product:edit" }
    methods:  [GET, POST]

admin_stock_edit:
    path:     /{id}/stockEdit
    defaults: { _controller: "AdminBundle:Product:editStock" }
    methods:  [GET, POST]

admin_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Product:delete" }
    methods:  DELETE

admin_product_alerts:
    path:     /alerts
    defaults: { _controller: "AdminBundle:Product:alerts" }
    methods:  GET
