app_admin_product:
    resource: "@AdminBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_search:
    path:     /search
    defaults: { _controller: AppBundle:App:search }

app_products_list:
    path:     /{type}/list
    defaults: { _controller: AppBundle:App:productsList }
    requirements:
        type: stationery|plastic

app_product_show:
    path: /product/{id}
    defaults: { _controller: AppBundle:App:product }
    requirements: 
        id: \d+

app_contact:
    path:   /contact
    defaults: { _controller: AppBundle:App:contact }
