app_cart_show:
    path:     /
    defaults: { _controller: AppBundle:Cart:showCart }

app_cart_add_product:
    path:     /add/product/{id}/{quantity}
    defaults: { _controller: AppBundle:Cart:addProduct, quantity: 1 }
    requirements:
        id: \d+
        quantity: \d+

app_cart_remove_product:
    path:     /remove/product/{id}
    defaults: { _controller: AppBundle:Cart:removeProduct }
    requirements:
        id: \d+
